In [1]:
import pandas as pd

In [2]:
person = {
 "first" : "corey",
 "last" : "schafer",
"email" :"coreyschafer@email.com"
}


people = {
 "first" : ["corey"],
 "last" : ["schafer"],
"email" : ["coreyschafer@email.com"]
}

people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [8]:
df['fullname'] = df['first']+' ' + df['last']

In [12]:
df

   first     last                   email       fullname
0  corey  schafer  coreyschafer@email.com  corey schafer
1   Jane      Doe       JaneDoe@email.com       Jane Doe
2   John      Doe       JohnDoe@email.com       John Doe

In [16]:
df.drop(columns = ['first', 'last'], inplace= True)

In [17]:
df

                    email       fullname
0  coreyschafer@email.com  corey schafer
1       JaneDoe@email.com       Jane Doe
2       JohnDoe@email.com       John Doe

In [19]:
df['fullname'].str.split(' ', expand = True)

       0        1
0  corey  schafer
1   Jane      Doe
2   John      Doe

In [20]:
df[['first', 'last']] = df['fullname'].str.split(' ', expand = True)

In [21]:
df

                    email       fullname  first     last
0  coreyschafer@email.com  corey schafer  corey  schafer
1       JaneDoe@email.com       Jane Doe   Jane      Doe
2       JohnDoe@email.com       John Doe   John      Doe

In [24]:
#add single row of data
new_row = pd.DataFrame([{
    'first': 'Tony',
    'last': 'Stark',
    'email': 'tony@email.com'
}])

df = pd.concat([df, new_row], ignore_index=True)

In [25]:
df

                    email       fullname  first     last
0  coreyschafer@email.com  corey schafer  corey  schafer
1       JaneDoe@email.com       Jane Doe   Jane      Doe
2       JohnDoe@email.com       John Doe   John      Doe
3          tony@email.com            NaN   Tony    Stark

In [27]:
people = {

    'first': ['Tony','Steve'],
    'last' : ['Stark', 'Rogers'],
    'email': ['tonystark@email.com', 'steverogers@email.com ']
}
df2 = pd.DataFrame(people)

In [28]:
df2

   first    last                   email
0   Tony   Stark     tonystark@email.com
1  Steve  Rogers  steverogers@email.com

In [32]:
df = pd.concat([df, df2], ignore_index=True)

In [33]:
df

                    email       fullname  first     last
0  coreyschafer@email.com  corey schafer  corey  schafer
1       JaneDoe@email.com       Jane Doe   Jane      Doe
2       JohnDoe@email.com       John Doe   John      Doe
3          tony@email.com            NaN   Tony    Stark
4     tonystark@email.com            NaN   Tony    Stark
5  steverogers@email.com             NaN  Steve   Rogers

In [34]:
df.drop(index = 4)

                    email       fullname  first     last
0  coreyschafer@email.com  corey schafer  corey  schafer
1       JaneDoe@email.com       Jane Doe   Jane      Doe
2       JohnDoe@email.com       John Doe   John      Doe
3          tony@email.com            NaN   Tony    Stark
5  steverogers@email.com             NaN  Steve   Rogers

In [35]:
filt = (df['last'] == 'Doe')

In [40]:
df.loc[filt,['email']]

               email
1  JaneDoe@email.com
2  JohnDoe@email.com

In [41]:
df.drop(index = df[filt].index)

                    email       fullname  first     last
0  coreyschafer@email.com  corey schafer  corey  schafer
3          tony@email.com            NaN   Tony    Stark
4     tonystark@email.com            NaN   Tony    Stark
5  steverogers@email.com             NaN  Steve   Rogers