In [1]:
import pandas as pd

In [2]:
person = {
 "first" : "corey",
 "last" : "schafer",
"email" :"coreyschafer@email.com"
}


people = {
 "first" : ["corey"],
 "last" : ["schafer"],
"email" : ["coreyschafer@email.com"]
}

people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [3]:
df = pd.DataFrame(people)

In [5]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [6]:
df.sort_values(by = 'last', ascending = True)

   first     last                   email
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com
0  corey  schafer  coreyschafer@email.com

In [11]:
df.sort_values(by = ['last', 'first'], ascending = [False, True], inplace = True)

In [12]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [13]:
df.sort_index()

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [14]:
df['last'].sort_values()

1        Doe
2        Doe
0    schafer
Name: last, dtype: object