In [ ]:
import pandas as pd
import numpy as np

In [2]:
people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [3]:
df = pd.DataFrame(people)

In [4]:
df.head()

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [12]:
#set the email as the index

df.set_index('email',inplace = True)

In [14]:
df

                        first     last
email
coreyschafer@email.com  corey  schafer
JaneDoe@email.com        Jane      Doe
JohnDoe@email.com        John      Doe

In [16]:
df.loc['coreyschafer@email.com','first']

'corey'

In [17]:
df.loc['coreyschafer@email.com']

first      corey
last     schafer
Name: coreyschafer@email.com, dtype: object

In [18]:
df.iloc[0]

first      corey
last     schafer
Name: coreyschafer@email.com, dtype: object

In [21]:
#reset the index
df.reset_index(inplace = True)

In [22]:
df.loc[0]

email    coreyschafer@email.com
first                     corey
last                    schafer
Name: 0, dtype: object