In [1]:
import pandas as pd
import numpy as np

In [2]:
people = {
 "first" : ['corey', 'Jane', 'John'],
 "last" : ['schafer', 'Doe', 'Doe'],
"email" : ['coreyschafer@email.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}

df = pd.DataFrame(people)

In [3]:
df

   first     last                   email
0  corey  schafer  coreyschafer@email.com
1   Jane      Doe       JaneDoe@email.com
2   John      Doe       JohnDoe@email.com

In [7]:
filt = (df['last'] == 'schafer')
df[filt].email

0    coreyschafer@email.com
Name: email, dtype: object

In [10]:
df.loc[filt]

   first     last                   email
0  corey  schafer  coreyschafer@email.com

In [ ]:
df.loc[filt,'email']

0    coreyschafer@email.com
Name: email, dtype: object

In [14]:
filt = (df['last'] == 'schafer') | (df['first'] == 'John')

In [ ]:
df.loc[~filt, 'email']

1    JaneDoe@email.com
Name: email, dtype: object

In [19]:
df.loc[~filt]

  first last              email
1  Jane  Doe  JaneDoe@email.com

In [22]:
df = pd.read_csv('C:\DSToolKits\data\survey_results_public.csv')

In [24]:
dff = pd.read_csv('C:\DSToolKits\data\survey_results_schema.csv')

In [26]:
dff.set_index('Column', inplace = True)

In [30]:
dff.loc['Country','QuestionText']

'In which country do you currently reside?'

In [32]:
df.Country.value_counts()

Country
United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...
Papua New Guinea                        1
Saint Kitts and Nevis                   1
Saint Vincent and the Grenadines        1
Sao Tome and Principe                   1
Chad                                    1
Name: count, Length: 179, dtype: int64

In [34]:
countries = ['United States', 'India', 'Germany', 'Canada']

In [35]:
filt = df['Country'].isin(countries)

In [39]:
df.loc[filt,'Country']

3        United States
5               Canada
7                India
9                India
11              Canada
             ...
88855           Canada
88859    United States
88864            India
88877    United States
88878           Canada
Name: Country, Length: 39271, dtype: object

In [51]:
programmingfilt = df['LanguageWorkedWith'].str.contains('Python',na = False)

In [53]:
df.loc[programmingfilt,'LanguageWorkedWith']

0                          HTML/CSS;Java;JavaScript;Python
1                                      C++;HTML/CSS;Python
3                                      C;C++;C#;Python;SQL
4              C++;HTML/CSS;Java;JavaScript;Python;SQL;VBA
7        Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
                               ...
88854    Bash/Shell/PowerShell;C;C++;HTML/CSS;Java;Java...
88860      Bash/Shell/PowerShell;C++;Python;Ruby;Other(s):
88865      Bash/Shell/PowerShell;HTML/CSS;Python;Other(s):
88872             C;C++;HTML/CSS;JavaScript;PHP;Python;SQL
88876                           HTML/CSS;JavaScript;Python
Name: LanguageWorkedWith, Length: 36443, dtype: object